import { Lesson } from '../types';

export const BUILT_IN_LESSONS: Lesson[] = [
  // BEGINNER
  {
    id: 'beginner-home-row-1',
    title: 'Home Row Foundation',
    category: 'beginner',
    difficulty: 'Easy',
    description: 'Master the core anchor keys: A S D F for the left hand and J K L ; for the right hand.',
    text: 'asdf jkl; asdf jkl; fdsa ;lkj aaaa jjjj ssss kkkk dddd llll ffff ;;;; sad lad fad ask flask fall lass',
    targetWpm: 25,
  },
  {
    id: 'beginner-home-row-words',
    title: 'Home Row Rhythm & Words',
    category: 'beginner',
    difficulty: 'Easy',
    description: 'Fluency drill using only home row combinations and common short words.',
    text: 'salad flash alfalfa flask fall falls lass dad fads glad add all asks salad fall dad ask lad flask',
    targetWpm: 30,
  },
  {
    id: 'beginner-top-row-1',
    title: 'Top Row: E and I Integration',
    category: 'beginner',
    difficulty: 'Easy',
    description: 'Expand your reach to the two most frequent vowel keys on the top row: E and I.',
    text: 'ed ik de ki ded kik see kid did fed led lie die silk side ride seek feel file dill desk life skill kids',
    targetWpm: 35,
  },
  {
    id: 'beginner-top-row-full',
    title: 'Full Top Row Mastery (QWERTYUIOP)',
    category: 'beginner',
    difficulty: 'Medium',
    description: 'Practice upper tier letters with standard finger reach and precision.',
    text: 'quit wire type rope pure poetry write quote power output trip equip repair tower properly equip priority query',
    targetWpm: 40,
  },
  {
    id: 'beginner-bottom-row',
    title: 'Bottom Row: Z X C V B N M',
    category: 'beginner',
    difficulty: 'Medium',
    description: 'Strengthen downward finger drops to conquer the bottom letter row.',
    text: 'zone calm van ban man next scan van box zinc comb blank view maze zinc cave cabin vine move verb',
    targetWpm: 35,
  },
  {
    id: 'beginner-numbers-symbols',
    title: 'Numbers & Common Symbols',
    category: 'beginner',
    difficulty: 'Hard',
    description: 'Top number row reaches along with punctuation: 1 2 3 4 5 6 7 8 9 0 ! @ # $ %',
    text: 'item #104 costs $25.50 at 80% discount! Call +1 (555) 019-2834 before 9:00 PM for a 100% money-back guarantee.',
    targetWpm: 35,
  },

  // COMMON ENGLISH WORDS
  {
    id: 'words-top-50',
    title: 'Top 50 Most Common Words',
    category: 'words',
    difficulty: 'Easy',
    description: 'The highest frequency words that make up over 40% of all written English.',
    text: 'the be to of and a in that have i it for not on with he as you do at this but his by from they we say her she or an will my one all would there their what so up out if about who get which go me',
    targetWpm: 50,
  },
  {
    id: 'words-fluency-100',
    title: '100 Core Vocabulary Sprint',
    category: 'words',
    difficulty: 'Medium',
    description: 'Build continuous touch typing cadence with diverse common word patterns.',
    text: 'time person year way day thing man world life hand part child eye woman place work week case point government company number group problem fact great little own other old right big high small large next early young few public bad',
    targetWpm: 60,
  },

  // FAMOUS QUOTES
  {
    id: 'quotes-steve-jobs',
    title: 'Steve Jobs: Stay Hungry',
    category: 'quotes',
    difficulty: 'Medium',
    description: 'Excerpt from the celebrated Stanford commencement address.',
    text: 'Your time is limited, so do not waste it living someone else\'s life. Don\'t be trapped by dogma, which is living with the results of other people\'s thinking. Stay hungry. Stay foolish.',
    targetWpm: 55,
  },
  {
    id: 'quotes-alan-turing',
    title: 'Alan Turing: Imitation & Mind',
    category: 'quotes',
    difficulty: 'Medium',
    description: 'Reflections from the pioneer of modern computing and artificial intelligence.',
    text: 'We can only see a short distance ahead, but we can see plenty there that needs to be done. Sometimes it is the people no one can imagine anything of who do the things no one can imagine.',
    targetWpm: 50,
  },
  {
    id: 'quotes-maya-angelou',
    title: 'Maya Angelou: Courage & Still I Rise',
    category: 'quotes',
    difficulty: 'Medium',
    description: 'Empowering lines exploring resilience and clarity of purpose.',
    text: 'You may not control all the events that happen to you, but you can decide not to be reduced by them. Try to be a rainbow in someone else\'s cloud. Do the best you can until you know better.',
    targetWpm: 50,
  },
  {
    id: 'quotes-einstein',
    title: 'Albert Einstein: Imagination',
    category: 'quotes',
    difficulty: 'Medium',
    description: 'A thoughtful reflection on curiosity and boundless creative thinking.',
    text: 'Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.',
    targetWpm: 50,
  },

  // CODE SNIPPETS
  {
    id: 'code-javascript-basics',
    title: 'JavaScript: Modern ES6 & Functions',
    category: 'code',
    difficulty: 'Hard',
    description: 'Practice curly braces, arrow functions, template literals, and array methods.',
    text: 'const calculateWpm = (chars, seconds) => {\n  const words = chars / 5;\n  const minutes = seconds / 60;\n  return Math.round(words / minutes) || 0;\n};',
    targetWpm: 45,
  },
  {
    id: 'code-python-data',
    title: 'Python: Comprehensions & Dictionaries',
    category: 'code',
    difficulty: 'Hard',
    description: 'Python syntax with colons, brackets, underscores, and indentation.',
    text: 'def analyze_performance(scores: list[float]) -> dict:\n    average = sum(scores) / len(scores)\n    return {"avg": round(average, 2), "top": max(scores)}',
    targetWpm: 45,
  },
  {
    id: 'code-html-semantic',
    title: 'HTML & CSS: Semantic Web Markup',
    category: 'code',
    difficulty: 'Medium',
    description: 'Angle brackets, attributes, classes, and closing tags.',
    text: '<header class="flex items-center justify-between px-6 py-4">\n  <h1 class="text-xl font-bold">TypePulse</h1>\n  <button type="button">Start</button>\n</header>',
    targetWpm: 45,
  },

  // SPEED BURSTS & PANGRAMS
  {
    id: 'speed-pangrams',
    title: 'Pangrams: Complete Alphabet Sprint',
    category: 'speed',
    difficulty: 'Medium',
    description: 'Classic sentences containing every single letter of the alphabet from A to Z.',
    text: 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump! Sphinx of black quartz, judge my vow.',
    targetWpm: 65,
  },
  {
    id: 'speed-sprint-short',
    title: 'Speed Sprint: Rapid Burst (30 Words)',
    category: 'speed',
    difficulty: 'Easy',
    description: 'Short and high-speed burst to test your maximum instantaneous words per minute.',
    text: 'focus on smooth relaxed fingers rather than rushing. speed will naturally emerge when accuracy and rhythm stay steady throughout each sentence.',
    targetWpm: 75,
  },
];
